#!/bin/sh
#
# Builds the doc, starts the mkdocs server and opens the page in
# firefox

cd docs
julia build.jl
cd ..
mkdocs build --clean
(sleep 1 && firefox http://127.0.0.1:8000)& # waits for mkdoc server to start up
mkdocs serve
